### ISSUE TITLE
Exception in read: invalid string character \U

### ISSUE THREAD

**Issue by vagreargnatry** [Release-Candidate/vscode-scheme-repl#1]
**Describe the bug**
When I press Ctrl+Enter, the following error occurs:
```
Exception in read: invalid string character \U
Exception: variable sersomenlDesktopchez-playgroundsample1.scm is not bound
Exception: variable λ> is not bound
Exception in read: unexpected end-of-file reading string
```

**To Reproduce**
1. I added `C:\Program Files\Chez Scheme 9.5.8\bin\ta6nt` to the user environment variable PATH.
2. Then I created a folder named "chez-playground" in `C:\Users\omenl\Desktop`.
3. In this folder, I created a file named `sample1.scm` and put the following code in it.
    ```scheme
    (define (fact n)
        (cond 
            [(< n 1) "error"] 
            [(= n 1) 1] 
            [else (* n (fact (sub1 n)))]))

    (define (fact-iter n)
        (define (iter cnt acc)
            (if (= cnt 1)
            acc
            (iter (sub1 cnt) (* cnt acc))))

        (cond
            [(< n 1) "error"]
            [else (iter n 1)]))
    ```
4. Place the mouse cursor at the end of the fifth line and press Ctrl+Enter.
5. This error occurred.

**Expected behavior**
Eval s-expression left of the cursor.

**Screenshots**
![1](https://github.com/Release-Candidate/vscode-scheme-repl/assets/104709852/1c267bca-3f7a-465b-8077-c4cc6e14ce13)

**Logs**
```
Chez Scheme REPL starting.
Registered all commands
Extension startup finished.
Sent 
    [else (* n (fact (sub1 n)))])) to REPL using command chezScheme.evalLastSexp
```

**Environment (please complete the following information):**
 - Version of the extension: `v0.1.0`
 - Version of VS Code: `1.79.2`
 - OS: `Windows 11 22H2`

**Additional context**
After trying the aforementioned steps, I created a new folder called `.vscode` within the directory and added a file named `.settings.json` inside it. In this file, I set the value of `chezScheme.schemePath` to `C:\\Program Files\\Chez Scheme 9.5.8\\bin\\ta6nt`. But the error still occurs.

**Comment by Release-Candidate** [comment]
Hi and thank you very much for your bug report.

I see. What is happening here is that I'm loading the source file using something like

```scheme
(load "C:\Users\omenl\Desktop")
```

and Chez thinks the `\U` is a non-existing escape sequence. I'm adding escaping of backslashes in file paths to the extension as soon as possible, I should be able to publish a new version today (until 00:00 CEST).

As a temporary workaround you can send the whole file to the interactive REPL by using a right click in the source file or the tab of the source file and selecting **Chez Scheme REPL: Send the whole current file to the REPL** or using the command **Chez Scheme REPL: Send the whole current file to the REPL**.

**Comment by Release-Candidate** [comment]
The new version 0.2.0 should fix this.
Could you please check if the error has gone away? I do not have Windows myself and can't test it.

### Download links: 

[VS Marketplace](https://marketplace.visualstudio.com/items?itemName=release-candidate.vscode-scheme-repl)
[Open VSX Marketplace](https://open-vsx.org/extension/Release-Candidate/vscode-scheme-repl)
[latest release at GitHub](https://github.com/Release-Candidate/vscode-scheme-repl/releases/latest)

**Comment by vagreargnatry** [comment]
Thank you! This error has been resolved.

**Comment by Release-Candidate** [comment]
Glad to hear, and thank you for your help!
