### ISSUE TITLE
REPL doesn't start if scheme path contains spaces (on win64)

### ISSUE THREAD

**Issue by tracker1398** [Release-Candidate/vscode-scheme-repl#28]
On win64 platform I use the following vscode settings:

_Settings -> Chez Scheme: Scheme Path_  
`C:\Program Files\Chez Scheme 10.0.0\bin\ta6nt\scheme.exe`

When I start a new REPL, I get the following message:

```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

The same thing happens when I hit Ctrl+Shift+Enter on an expression.

If I copy the scheme system to a directory without spaces, everything works fine.

**Comment by Release-Candidate** [comment]
But inline evaluation and autocompletion works for you, right? I do not have Windows, but here spaces in the scheme path work with the "internal" REPL, but not when sending to the terminal REPL.

**Comment by tracker1398** [comment]
Exactly. The inline evaluation and the autocompletion works well in all situations.

**Comment by Release-Candidate** [comment]
Great, thanks. I'm trying to escape the spaces and publish a new version. I'm going to post here when it is ready for a test.

**Comment by Release-Candidate** [comment]
Could you please check the new version 0.7.3 if that is working now?

**Comment by tracker1398** [comment]
It works fine now.
Thanks!

**Comment by monospod** [comment]
Unfortunately this seems to break having `scheme` on the `PATH` in Windows. When I launch `Chez Scheme REPL: Start REPL` I get this in the terminal:
```
PS C:\Users\monospod\Documents\projects\play-with-ffi> "scheme"
scheme
PS C:\Users\monospod\Documents\projects\play-with-ffi> (waiter-prompt-string "λ>")
waiter-prompt-string : The term 'waiter-prompt-string' is not recognized as 
...
```

However, without the quotation marks it finds `scheme` in my path:
``` 
PS C:\Users\monospod\Documents\projects\play-with-ffi> scheme
Chez Scheme Version 10.0.0
Copyright 1984-2024 Cisco Systems, Inc.

> 
```

This means that the default setting doesn't work on Windows as you'd need to replace it with the full path to scheme?

_(Thanks for the extension.)_

**Comment by Release-Candidate** [comment]
Thanks for the bug report.

I see, so I'm going to check if the given path contains spaces, and only add the double quotes, if yes.

**Comment by monospod** [comment]
I think tracker1398's terminal might be the command prompt, where-as mine is PowerShell.

The command prompt works for both `"scheme"` on the path, and the quoted full path. *Neither* quoted version works with PowerShell, but the unquoted `scheme` on the path does (confirmed by rolling back to 0.7.2).

Your planned solution for `scheme` found on the path should work in both PowerShell and the Command Line.

If someone needs to give the full path (with, or without spaces), then they'd need to set the default terminal in the Visual Studio Code preferences to be the Command Prompt: `Terminal > Integrated > Default Profile: Windows`, as it wouldn't work in PowerShell.

**Comment by Release-Candidate** [comment]
Thank you very much for the information, I'm going to add that to the README.

**Comment by Release-Candidate** [comment]
There is a new version, 0.7.4, which should fix that problem.

I ended up always using `cmd.exe` and Windows for the pane REPL and removing any unnecessary single or double quotes.

**Comment by monospod** [comment]
Thanks - that's perfect.

I've checked that I still have PowerShell as my default terminal, and that the REPL in the new version launches with the command prompt instead. It works with scheme on my path (and doesn't quote it), and when I used the full path with spaces it quoted it and ran correctly too.

**Comment by Release-Candidate** [comment]
Great to hear and thank you for the feedback, really appreciated!
